# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Transition_Plugin
                                 A QGIS plugin
 This plugin allows the communication with the transition interface
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-06
        copyright            : (C) 2024 by Manel
        email                : manel.keddam@polymtl.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Transition_Plugin class from file Transition_Plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .transition_plugin import Transition_Plugin
    return Transition_Plugin(iface)
